//
//  Card.swift
//  Cards Against Humanity Core
//
//  Created by Ezekiel Elin on 7/23/15.
//  Copyright © 2015 Ezekiel Elin. All rights reserved.
//

func ==(a: Game.Card, b: Game.Card) -> Bool {
    return a.text == b.text
}

extension Game {
    class Card: Equatable, CustomStringConvertible {
        let text: String
        init(text t: String) {
            self.text = t
        }
        var description: String {
            return self.text
        }
    }
    
    class WhiteCard: Card {}
    
    class BlackCard: Card {
        let pick: Int
        init(text t: String, pick p: Int) {
            self.pick = p
            super.init(text: t)
        }
    }
    
    static func buildBlackCardList() -> [BlackCard] {
        return [
            BlackCard(text:"Why can't I sleep at night?",pick:1),
            BlackCard(text:"I got 99 problems but _ ain't one.",pick:1),
            BlackCard(text:"What's a girl's best friend?",pick:1),
            BlackCard(text:"What's that smell?",pick:1),
            BlackCard(text:"This is the way the world ends / This is the way the world ends / Not with a bang but with _.",pick:1),
            BlackCard(text:"What is Batman's guilty pleasure?",pick:1),
            BlackCard(text:"TSA guidelines now prohibit _ on airplanes.",pick:1),
            BlackCard(text:"What ended my last relationship?",pick:1),
            BlackCard(text:"MTV's new reality show features eight washed-up celebrities living with _.",pick:1),
            BlackCard(text:"I drink to forget _.",pick:1),
            BlackCard(text:"I'm sorry, Professor, but I couldn't complete my homework because of _.",pick:1),
            BlackCard(text:"Alternative medicine is now embracing the curative powers of _.",pick:1),
            BlackCard(text:"What's that sound?",pick:1),
            BlackCard(text:"What's the next Happy Meal&reg; toy?",pick:1),
            BlackCard(text:"It's a pity that kids these days are all getting involved with _.",pick:1),
            BlackCard(text:"In the new Disney Channel Original Movie, Hannah Montana struggles with _ for the first time.",pick:1),
            BlackCard(text:"_. That's how I want to die.",pick:1),
            BlackCard(text:"What does Dick Cheney prefer?",pick:1),
            BlackCard(text:"What's the most emo?",pick:1),
            BlackCard(text:"Instead of coal, Santa now gives the bad children _.",pick:1),
            BlackCard(text:"Next from J.K. Rowling: Harry Potter and the Chamber of _.",pick:1),
            BlackCard(text:"A romantic, candlelit dinner would be incomplete without _.",pick:1),
            BlackCard(text:"White people like _.",pick:1),
            BlackCard(text:"_. Betcha can't have just one!",pick:1),
            BlackCard(text:"War!\n\nWhat is it good for?",pick:1),
            BlackCard(text:"BILLY MAYS HERE FOR _.",pick:1),
            BlackCard(text:"_. High five, bro.",pick:1),
            BlackCard(text:"During sex, I like to think about _.",pick:1),
            BlackCard(text:"What did I bring back from Mexico?",pick:1),
            BlackCard(text:"What are my parents hiding from me?",pick:1),
            BlackCard(text:"What will always get you laid?",pick:1),
            BlackCard(text:"What would grandma find disturbing, yet oddly charming?",pick:1),
            BlackCard(text:"What did the U.S. airdrop to the children of Afghanistan?",pick:1),
            BlackCard(text:"What helps Obama unwind?",pick:1),
            BlackCard(text:"What's there a ton of in heaven?",pick:1),
            BlackCard(text:"Major League Baseball has banned _ for giving players an unfair advantage.",pick:1),
            BlackCard(text:"When I am a billionaire, I shall erect a 50-foot statue to commemorate _.",pick:1),
            BlackCard(text:"What's the new fad diet?",pick:1),
            BlackCard(text:"When I am the President of the United States, I will create the Department of _.",pick:1),
            BlackCard(text:"_. It's a trap!",pick:1),
            BlackCard(text:"How am I maintaining my relationship status?",pick:1),
            BlackCard(text:"What will I bring back in time to convince people that I am a powerful wizard?",pick:1),
            BlackCard(text:"While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on _.",pick:1),
            BlackCard(text:"Coming to Broadway this season, _: The Musical.",pick:1),
            BlackCard(text:"What's my secret power?",pick:1),
            BlackCard(text:"What gives me uncontrollable gas?",pick:1),
            BlackCard(text:"But before I kill you, Mr. Bond, I must show you _.",pick:1),
            BlackCard(text:"What never fails to liven up the party?",pick:1),
            BlackCard(text:"What am I giving up for Lent?",pick:1),
            BlackCard(text:"What do old people smell like? ",pick:1),
            BlackCard(text:"The class field trip was completely ruined by _.",pick:1),
            BlackCard(text:"When Pharaoh remained unmoved, Moses called down a plague of _.",pick:1),
            BlackCard(text:"I do not know with which weapons World War III will be fought, but World War IV will be fought with _.",pick:1),
            BlackCard(text:"What's Teach for America using to inspire inner city students to succeed?",pick:1),
            BlackCard(text:"In Michael Jackson's final moments, he thought about _.",pick:1),
            BlackCard(text:"Why do I hurt all over?",pick:1),
            BlackCard(text:"Studies show that lab rats navigate mazes 50% faster after being exposed to _.",pick:1),
            BlackCard(text:"Why am I sticky?",pick:1),
            BlackCard(text:"What's my anti-drug?",pick:1),
            BlackCard(text:"And the Academy Award for _ goes to _.",pick:2),
            BlackCard(text:"For my next trick, I will pull _ out of _.",pick:2),
            BlackCard(text:"_: Good to the last drop.",pick:1),
            BlackCard(text:"What did Vin Diesel eat for dinner?",pick:1),
            BlackCard(text:"_: kid-tested, mother-approved.",pick:1),
            BlackCard(text:"What gets better with age?",pick:1),
            BlackCard(text:"I never truly understood _ until I encountered _.",pick:2),
            BlackCard(text:"Rumor has it that Vladimir Putin's favorite delicacy is _ stuffed with _.",pick:2),
            BlackCard(text:"Lifetime&reg; presents _, the story of _.",pick:2),
            BlackCard(text:"Make a haiku.",pick:3),
            BlackCard(text:"In M. Night Shyamalan's new movie, Bruce Willis discovers that _ had really been _ all along.",pick:2),
            BlackCard(text:"_ is a slippery slope that leads to _.",pick:2),
            BlackCard(text:"In a world ravaged by _, our only solace is _.",pick:2),
            BlackCard(text:"That's right, I killed _. How, you ask? _.",pick:2),
            BlackCard(text:"When I was tripping on acid, _ turned into _.",pick:2),
            BlackCard(text:"_ + _ = _.",pick:3),
            BlackCard(text:"What's the next superhero/sidekick duo?",pick:2),
            BlackCard(text:"Dear Abby,\n\nI'm having some trouble with _ and would like your advice.",pick:1),
            BlackCard(text:"After the earthquake, Sean Penn brought _ to the people of Haiti.",pick:1),
            BlackCard(text:"In L.A. County Jail, word is you can trade 200 cigarettes for _.",pick:1),
            BlackCard(text:"Maybe she's born with it. Maybe it's _.",pick:1),
            BlackCard(text:"Life for American Indians was forever changed when the White Man introduced them to _.",pick:1),
            BlackCard(text:"Next on ESPN2, the World Series of _.",pick:1),
            BlackCard(text:"Step 1: _. Step 2: _. Step 3: Profit.",pick:2),
            BlackCard(text:"Here is the church<br>Here is the steeple<br>Open the doors<br>And there is _.",pick:1),
            BlackCard(text:"How did I lose my virginity?",pick:1),
            BlackCard(text:"During his childhood, Salvador Dalí produced hundreds of paintings of _.",pick:1),
            BlackCard(text:"In 1,000 years, when paper money is a distant memory, how will we pay for goods and services?",pick:1),
            BlackCard(text:"What don't you want to find in your Kung Pao chicken?",pick:1),
            BlackCard(text:"The Smithsonian Museum of Natural History has just opened an exhibit on _.",pick:1),
            BlackCard(text:"Daddy, why is Mommy crying?",pick:1)
        ]
    }
    
    static func buildWhiteCardList()->[WhiteCard] {
        return [
            WhiteCard(text: "Coat hanger abortions."),
            WhiteCard(text: "Man meat."),
            WhiteCard(text: "Autocannibalism."),
            WhiteCard(text: "Vigorous jazz hands."),
            WhiteCard(text: "Flightless birds."),
            WhiteCard(text: "Pictures of boobs."),
            WhiteCard(text: "Doing the right thing."),
            WhiteCard(text: "The violation of our most basic human rights."),
            WhiteCard(text: "Viagra®."),
            WhiteCard(text: "Self-loathing."),
            WhiteCard(text: "Spectacular abs."),
            WhiteCard(text: "A balanced breakfast."),
            WhiteCard(text: "Roofies."),
            WhiteCard(text: "Concealing a boner."),
            WhiteCard(text: "Amputees."),
            WhiteCard(text: "The Big Bang."),
            WhiteCard(text: "Former President George W. Bush."),
            WhiteCard(text: "The Rev. Dr. Martin Luther King, Jr."),
            WhiteCard(text: "Smegma."),
            WhiteCard(text: "Being marginalized."),
            WhiteCard(text: "Cuddling."),
            WhiteCard(text: "Laying an egg."),
            WhiteCard(text: "The Pope."),
            WhiteCard(text: "Aaron Burr."),
            WhiteCard(text: "Genital piercings."),
            WhiteCard(text: "Fingering."),
            WhiteCard(text: "A bleached asshole."),
            WhiteCard(text: "Horse meat."),
            WhiteCard(text: "Fear itself."),
            WhiteCard(text: "Science."),
            WhiteCard(text: "Elderly Japanese men."),
            WhiteCard(text: "Stranger danger."),
            WhiteCard(text: "The terrorists."),
            WhiteCard(text: "Praying the gay away."),
            WhiteCard(text: "Same-sex ice dancing."),
            WhiteCard(text: "Ethnic cleansing."),
            WhiteCard(text: "Cheating in the Special Olympics."),
            WhiteCard(text: "German dungeon porn."),
            WhiteCard(text: "Bingeing and purging."),
            WhiteCard(text: "Making a pouty face."),
            WhiteCard(text: "William Shatner."),
            WhiteCard(text: "Heteronormativity."),
            WhiteCard(text: "Nickelback."),
            WhiteCard(text: "Tom Cruise."),
            WhiteCard(text: "The profoundly handicapped."),
            WhiteCard(text: "The placenta."),
            WhiteCard(text: "Chainsaws for hands."),
            WhiteCard(text: "Arnold Schwarzenegger."),
            WhiteCard(text: "An icepick lobotomy."),
            WhiteCard(text: "Goblins."),
            WhiteCard(text: "Object permanence."),
            WhiteCard(text: "Dying."),
            WhiteCard(text: "Foreskin."),
            WhiteCard(text: "A falcon with a cap on its head."),
            WhiteCard(text: "Hormone injections."),
            WhiteCard(text: "Dying of dysentery."),
            WhiteCard(text: "Sexy pillow fights."),
            WhiteCard(text: "The invisible hand."),
            WhiteCard(text: "A really cool hat."),
            WhiteCard(text: "Sean Penn."),
            WhiteCard(text: "Heartwarming orphans."),
            WhiteCard(text: "The clitoris."),
            WhiteCard(text: "The Three-Fifths compromise."),
            WhiteCard(text: "A sad handjob."),
            WhiteCard(text: "Men."),
            WhiteCard(text: "Historically black colleges."),
            WhiteCard(text: "A micropenis."),
            WhiteCard(text: "Raptor attacks."),
            WhiteCard(text: "Agriculture."),
            WhiteCard(text: "Vikings."),
            WhiteCard(text: "Pretending to care."),
            WhiteCard(text: "The Underground Railroad."),
            WhiteCard(text: "My humps."),
            WhiteCard(text: "Being a dick to children."),
            WhiteCard(text: "Geese."),
            WhiteCard(text: "Bling."),
            WhiteCard(text: "Sniffing glue."),
            WhiteCard(text: "The South."),
            WhiteCard(text: "An Oedipus complex."),
            WhiteCard(text: "Eating all of the cookies before the AIDS bake-sale."),
            WhiteCard(text: "Sexting."),
            WhiteCard(text: "YOU MUST CONSTRUCT ADDITIONAL PYLONS."),
            WhiteCard(text: "Mutually-assured destruction."),
            WhiteCard(text: "Sunshine and rainbows."),
            WhiteCard(text: "Count Chocula."),
            WhiteCard(text: "Sharing needles."),
            WhiteCard(text: "Being rich."),
            WhiteCard(text: "Skeletor."),
            WhiteCard(text: "A sausage festival."),
            WhiteCard(text: "Michael Jackson."),
            WhiteCard(text: "Emotions."),
            WhiteCard(text: "Farting and walking away."),
            WhiteCard(text: "The Chinese gymnastics team."),
            WhiteCard(text: "Necrophilia."),
            WhiteCard(text: "Spontaneous human combustion."),
            WhiteCard(text: "Yeast."),
            WhiteCard(text: "Leaving an awkward voicemail."),
            WhiteCard(text: "Dick Cheney."),
            WhiteCard(text: "White people."),
            WhiteCard(text: "Penis envy."),
            WhiteCard(text: "Teaching a robot to love."),
            WhiteCard(text: "Sperm whales."),
            WhiteCard(text: "Scrubbing under the folds."),
            WhiteCard(text: "Panda sex."),
            WhiteCard(text: "Whipping it out."),
            WhiteCard(text: "Catapults."),
            WhiteCard(text: "Masturbation."),
            WhiteCard(text: "Natural selection."),
            WhiteCard(text: "Opposable thumbs."),
            WhiteCard(text: "A sassy black woman."),
            WhiteCard(text: "AIDS."),
            WhiteCard(text: "The KKK."),
            WhiteCard(text: "Figgy pudding."),
            WhiteCard(text: "Seppuku."),
            WhiteCard(text: "Gandhi."),
            WhiteCard(text: "Preteens."),
            WhiteCard(text: "Toni Morrison's vagina."),
            WhiteCard(text: "Five-Dollar Footlongs&trade;."),
            WhiteCard(text: "Land mines."),
            WhiteCard(text: "A sea of troubles."),
            WhiteCard(text: "A zesty breakfast burrito."),
            WhiteCard(text: "Christopher Walken."),
            WhiteCard(text: "Friction."),
            WhiteCard(text: "Balls."),
            WhiteCard(text: "Dental dams."),
            WhiteCard(text: "A can of whoop-ass."),
            WhiteCard(text: "A tiny horse."),
            WhiteCard(text: "Waiting 'til marriage."),
            WhiteCard(text: "Authentic Mexican cuisine."),
            WhiteCard(text: "Genghis Khan."),
            WhiteCard(text: "Old-people smell."),
            WhiteCard(text: "Feeding Rosie O'Donnell."),
            WhiteCard(text: "Pixelated bukkake."),
            WhiteCard(text: "Friends with benefits."),
            WhiteCard(text: "The token minority."),
            WhiteCard(text: "The Tempur-Pedic&reg; Swedish Sleep System&trade;."),
            WhiteCard(text: "A thermonuclear detonation."),
            WhiteCard(text: "Take-backsies."),
            WhiteCard(text: "The Rapture."),
            WhiteCard(text: "A cooler full of organs."),
            WhiteCard(text: "Sweet, sweet vengeance."),
            WhiteCard(text: "RoboCop."),
            WhiteCard(text: "Keanu Reeves."),
            WhiteCard(text: "Drinking alone."),
            WhiteCard(text: "Giving 110%."),
            WhiteCard(text: "Flesh-eating bacteria."),
            WhiteCard(text: "The American Dream."),
            WhiteCard(text: "Taking off your shirt."),
            WhiteCard(text: "Me time."),
            WhiteCard(text: "A murder most foul."),
            WhiteCard(text: "The inevitable heat death of the universe."),
            WhiteCard(text: "The folly of man."),
            WhiteCard(text: "That thing that electrocutes your abs."),
            WhiteCard(text: "Cards Against Humanity."),
            WhiteCard(text: "Fiery poops."),
            WhiteCard(text: "Poor people."),
            WhiteCard(text: "Edible underpants."),
            WhiteCard(text: "Britney Spears at 55."),
            WhiteCard(text: "All-you-can-eat shrimp for $4.99."),
            WhiteCard(text: "Pooping back and forth. Forever."),
            WhiteCard(text: "Fancy Feast&reg;."),
            WhiteCard(text: "Jewish fraternities."),
            WhiteCard(text: "Being a motherfucking sorcerer."),
            WhiteCard(text: "Pulling out."),
            WhiteCard(text: "Picking up girls at the abortion clinic."),
            WhiteCard(text: "The homosexual agenda."),
            WhiteCard(text: "The Holy Bible."),
            WhiteCard(text: "Passive-agression."),
            WhiteCard(text: "Ronald Reagan."),
            WhiteCard(text: "Vehicular manslaughter."),
            WhiteCard(text: "Nipple blades."),
            WhiteCard(text: "Assless chaps."),
            WhiteCard(text: "Full frontal nudity."),
            WhiteCard(text: "Hulk Hogan."),
            WhiteCard(text: "Daddy issues."),
            WhiteCard(text: "The hardworking Mexican."),
            WhiteCard(text: "Natalie Portman."),
            WhiteCard(text: "Waking up half-naked in a Denny's parking lot."),
            WhiteCard(text: "God."),
            WhiteCard(text: "Sean Connery."),
            WhiteCard(text: "Saxophone solos."),
            WhiteCard(text: "Gloryholes."),
            WhiteCard(text: "The World of Warcraft."),
            WhiteCard(text: "Homeless people."),
            WhiteCard(text: "Scalping."),
            WhiteCard(text: "Darth Vader."),
            WhiteCard(text: "Eating the last known bison."),
            WhiteCard(text: "Guys who don't call."),
            WhiteCard(text: "Hot Pockets&reg;."),
            WhiteCard(text: "A time travel paradox."),
            WhiteCard(text: "The milk man."),
            WhiteCard(text: "Testicular torsion."),
            WhiteCard(text: "Dropping a chandelier on your enemies and riding the rope up."),
            WhiteCard(text: "World peace."),
            WhiteCard(text: "A salty surprise."),
            WhiteCard(text: "Poorly-timed Holocaust jokes."),
            WhiteCard(text: "Smallpox blankets."),
            WhiteCard(text: "Licking things to claim them as your own."),
            WhiteCard(text: "The heart of a child."),
            WhiteCard(text: "Robert Downey, Jr."),
            WhiteCard(text: "Lockjaw."),
            WhiteCard(text: "Eugenics."),
            WhiteCard(text: "A good sniff."),
            WhiteCard(text: "Friendly fire."),
            WhiteCard(text: "The taint; the grundle; the fleshy fun-bridge."),
            WhiteCard(text: "Wearing underwear inside-out to avoid doing laundry."),
            WhiteCard(text: "Hurricane Katrina."),
            WhiteCard(text: "Free samples."),
            WhiteCard(text: "Jerking off into a pool of children's tears."),
            WhiteCard(text: "A foul mouth."),
            WhiteCard(text: "The glass ceiling."),
            WhiteCard(text: "Republicans."),
            WhiteCard(text: "Explosions."),
            WhiteCard(text: "Michelle Obama's arms."),
            WhiteCard(text: "Getting really high."),
            WhiteCard(text: "Attitude."),
            WhiteCard(text: "Sarah Palin."),
            WhiteCard(text: "The &Uuml;bermensch."),
            WhiteCard(text: "Altar boys."),
            WhiteCard(text: "My soul."),
            WhiteCard(text: "My sex life."),
            WhiteCard(text: "Pedophiles."),
            WhiteCard(text: "72 virgins."),
            WhiteCard(text: "Pabst Blue Ribbon."),
            WhiteCard(text: "Domino's&trade; Oreo&trade; Dessert Pizza."),
            WhiteCard(text: "A snapping turtle biting the tip of your penis."),
            WhiteCard(text: "The Blood of Christ."),
            WhiteCard(text: "Half-assed foreplay."),
            WhiteCard(text: "My collection of high-tech sex toys."),
            WhiteCard(text: "A middle-aged man on roller skates."),
            WhiteCard(text: "Bitches."),
            WhiteCard(text: "Bill Nye the Science Guy."),
            WhiteCard(text: "Italians."),
            WhiteCard(text: "A windmill full of corpses."),
            WhiteCard(text: "Adderall&trade;."),
            WhiteCard(text: "Crippling debt."),
            WhiteCard(text: "A stray pube."),
            WhiteCard(text: "Prancing."),
            WhiteCard(text: "Passing a kidney stone."),
            WhiteCard(text: "A brain tumor."),
            WhiteCard(text: "Leprosy."),
            WhiteCard(text: "Puppies!"),
            WhiteCard(text: "Bees?"),
            WhiteCard(text: "Frolicking."),
            WhiteCard(text: "Repression."),
            WhiteCard(text: "Road head."),
            WhiteCard(text: "A bag of magic beans."),
            WhiteCard(text: "An asymmetric boob job."),
            WhiteCard(text: "Dead parents."),
            WhiteCard(text: "Public ridicule."),
            WhiteCard(text: "A mating display."),
            WhiteCard(text: "A mime having a stroke."),
            WhiteCard(text: "Stephen Hawking talking dirty."),
            WhiteCard(text: "African children."),
            WhiteCard(text: "Mouth herpes."),
            WhiteCard(text: "Overcompensation."),
            WhiteCard(text: "Riding off into the sunset."),
            WhiteCard(text: "Being on fire."),
            WhiteCard(text: "Tangled Slinkys."),
            WhiteCard(text: "Civilian casualties."),
            WhiteCard(text: "Auschwitz."),
            WhiteCard(text: "My genitals."),
            WhiteCard(text: "Not reciprocating oral sex."),
            WhiteCard(text: "Lactation."),
            WhiteCard(text: "Being fabulous."),
            WhiteCard(text: "Shaquille O'Neal's acting career."),
            WhiteCard(text: "My relationship status."),
            WhiteCard(text: "Asians who aren't good at math."),
            WhiteCard(text: "Alcoholism."),
            WhiteCard(text: "Incest."),
            WhiteCard(text: "Grave robbing."),
            WhiteCard(text: "Hope."),
            WhiteCard(text: "8 oz. of sweet Mexican black-tar heroin."),
            WhiteCard(text: "Kids with ass cancer."),
            WhiteCard(text: "Winking at old people."),
            WhiteCard(text: "The Jews."),
            WhiteCard(text: "Justin Bieber."),
            WhiteCard(text: "Doin' it in the butt."),
            WhiteCard(text: "A lifetime of sadness."),
            WhiteCard(text: "The Hamburglar."),
            WhiteCard(text: "Swooping."),
            WhiteCard(text: "Classist undertones."),
            WhiteCard(text: "New Age music."),
            WhiteCard(text: "Not giving a shit about the Third World."),
            WhiteCard(text: "The Kool-Aid Man."),
            WhiteCard(text: "A hot mess."),
            WhiteCard(text: "Tentacle porn."),
            WhiteCard(text: "Lumberjack fantasies."),
            WhiteCard(text: "The gays."),
            WhiteCard(text: "Scientology."),
            WhiteCard(text: "Estrogen."),
            WhiteCard(text: "GoGurt&reg;."),
            WhiteCard(text: "Judge Judy."),
            WhiteCard(text: "Dick fingers."),
            WhiteCard(text: "Racism."),
            WhiteCard(text: "Surprise sex!"),
            WhiteCard(text: "Police brutality."),
            WhiteCard(text: "Passable transvestites."),
            WhiteCard(text: "The Virginia Tech Massacre."),
            WhiteCard(text: "When you fart and a little bit comes out."),
            WhiteCard(text: "Oompa-Loompas."),
            WhiteCard(text: "A fetus."),
            WhiteCard(text: "Obesity."),
            WhiteCard(text: "Tasteful sideboob."),
            WhiteCard(text: "Hot people."),
            WhiteCard(text: "BATMAN!!!"),
            WhiteCard(text: "Black people."),
            WhiteCard(text: "A gassy antelope."),
            WhiteCard(text: "Sexual tension."),
            WhiteCard(text: "Third base."),
            WhiteCard(text: "Racially-biased SAT questions."),
            WhiteCard(text: "Porn stars."),
            WhiteCard(text: "A Super Soaker&trade; full of cat pee."),
            WhiteCard(text: "Muhammed (Praise Be Unto Him)."),
            WhiteCard(text: "Puberty."),
            WhiteCard(text: "A disappointing birthday party."),
            WhiteCard(text: "An erection that lasts longer than four hours."),
            WhiteCard(text: "White privilege."),
            WhiteCard(text: "Getting so angry that you pop a boner."),
            WhiteCard(text: "Wifely duties."),
            WhiteCard(text: "Two midgets shitting into a bucket."),
            WhiteCard(text: "Queefing."),
            WhiteCard(text: "Wiping her butt."),
            WhiteCard(text: "Golden showers."),
            WhiteCard(text: "Barack Obama."),
            WhiteCard(text: "Nazis."),
            WhiteCard(text: "A robust mongoloid."),
            WhiteCard(text: "An M. Night Shyamalan plot twist."),
            WhiteCard(text: "Getting drunk on mouthwash."),
            WhiteCard(text: "Lunchables&trade;."),
            WhiteCard(text: "Women in yogurt commercials."),
            WhiteCard(text: "John Wilkes Booth."),
            WhiteCard(text: "Powerful thighs."),
            WhiteCard(text: "Mr. Clean, right behind you."),
            WhiteCard(text: "Multiple stab wounds."),
            WhiteCard(text: "Cybernetic enhancements."),
            WhiteCard(text: "Serfdom."),
            WhiteCard(text: "Kanye West."),
            WhiteCard(text: "Women's suffrage."),
            WhiteCard(text: "Children on leashes."),
            WhiteCard(text: "Harry Potter erotica."),
            WhiteCard(text: "The Dance of the Sugar Plum Fairy."),
            WhiteCard(text: "Lance Armstrong's missing testicle."),
            WhiteCard(text: "Parting the Red Sea."),
            WhiteCard(text: "The Amish."),
            WhiteCard(text: "Dead babies."),
            WhiteCard(text: "Child beauty pageants."),
            WhiteCard(text: "AXE Body Spray."),
            WhiteCard(text: "Centaurs."),
            WhiteCard(text: "Copping a feel."),
            WhiteCard(text: "Grandma."),
            WhiteCard(text: "Famine."),
            WhiteCard(text: "The Trail of Tears."),
            WhiteCard(text: "The miracle of childbirth."),
            WhiteCard(text: "Finger painting."),
            WhiteCard(text: "A monkey smoking a cigar."),
            WhiteCard(text: "The Make-A-Wish&reg; Foundation."),
            WhiteCard(text: "Anal beads."),
            WhiteCard(text: "The Force."),
            WhiteCard(text: "Kamikaze pilots."),
            WhiteCard(text: "Dry heaving."),
            WhiteCard(text: "Active listening."),
            WhiteCard(text: "Ghosts."),
            WhiteCard(text: "The Hustle."),
            WhiteCard(text: "Peeing a little bit."),
            WhiteCard(text: "Another goddamn vampire movie."),
            WhiteCard(text: "Shapeshifters."),
            WhiteCard(text: "The Care Bear Stare."),
            WhiteCard(text: "Hot cheese."),
            WhiteCard(text: "A mopey zoo lion."),
            WhiteCard(text: "A defective condom."),
            WhiteCard(text: "Teenage pregnancy."),
            WhiteCard(text: "A Bop It&trade;."),
            WhiteCard(text: "Expecting a burp and vomiting on the floor."),
            WhiteCard(text: "Horrifying laser hair removal accidents."),
            WhiteCard(text: "Boogers."),
            WhiteCard(text: "Unfathomable stupidity."),
            WhiteCard(text: "Breaking out into song and dance."),
            WhiteCard(text: "Soup that is too hot."),
            WhiteCard(text: "Morgan Freeman's voice."),
            WhiteCard(text: "Getting naked and watching Nickelodeon."),
            WhiteCard(text: "MechaHitler."),
            WhiteCard(text: "Flying sex snakes."),
            WhiteCard(text: "The true meaning of Christmas."),
            WhiteCard(text: "My inner demons."),
            WhiteCard(text: "Pac-Man uncontrollably guzzling cum."),
            WhiteCard(text: "My vagina."),
            WhiteCard(text: "A homoerotic volleyball montage."),
            WhiteCard(text: "Actually taking candy from a baby."),
            WhiteCard(text: "Crystal meth."),
            WhiteCard(text: "Exactly what you'd expect."),
            WhiteCard(text: "Natural male enhancement."),
            WhiteCard(text: "Passive-aggressive Post-it notes."),
            WhiteCard(text: "Inappropriate yodeling."),
            WhiteCard(text: "Lady Gaga."),
            WhiteCard(text: "The Little Engine That Could."),
            WhiteCard(text: "Vigilante justice."),
            WhiteCard(text: "A death ray."),
            WhiteCard(text: "Poor life choices."),
            WhiteCard(text: "A gentle caress of the inner thigh."),
            WhiteCard(text: "Embryonic stem cells."),
            WhiteCard(text: "Nicolas Cage."),
            WhiteCard(text: "Firing a rifle into the air while balls deep in a squealing hog."),
            WhiteCard(text: "Switching to Geico&reg;."),
            WhiteCard(text: "The chronic."),
            WhiteCard(text: "Erectile dysfunction."),
            WhiteCard(text: "Home video of Oprah sobbing into a Lean Cuisine&reg;."),
            WhiteCard(text: "A bucket of fish heads."),
            WhiteCard(text: "50,000 volts straight to the nipples."),
            WhiteCard(text: "Being fat and stupid."),
            WhiteCard(text: "Hospice care."),
            WhiteCard(text: "A pyramid of severed heads."),
            WhiteCard(text: "Getting married, having a few kids, buying some stuff, retiring to Florida, and dying."),
            WhiteCard(text: "A subscription to Men's Fitness."),
            WhiteCard(text: "Crucifixion."),
            WhiteCard(text: "A micropig wearing a tiny raincoat and booties."),
            WhiteCard(text: "Some god-damn peace and quiet."),
            WhiteCard(text: "Used panties."),
            WhiteCard(text: "A tribe of warrior women."),
            WhiteCard(text: "The penny whistle solo from \"My Heart Will Go On.\""),
            WhiteCard(text: "An oversized lollipop."),
            WhiteCard(text: "Helplessly giggling at the mention of Hutus and Tutsis."),
            WhiteCard(text: "Not wearing pants."),
            WhiteCard(text: "Consensual sex."),
            WhiteCard(text: "Her Majesty, Queen Elizabeth II."),
            WhiteCard(text: "Funky fresh rhymes."),
            WhiteCard(text: "The art of seduction."),
            WhiteCard(text: "The Devil himself."),
            WhiteCard(text: "Advice from a wise, old black man."),
            WhiteCard(text: "Destroying the evidence."),
            WhiteCard(text: "The light of a billion suns."),
            WhiteCard(text: "Wet dreams."),
            WhiteCard(text: "Synergistic management solutions."),
            WhiteCard(text: "Growing a pair."),
            WhiteCard(text: "Silence."),
            WhiteCard(text: "An M16 assault rifle."),
            WhiteCard(text: "Poopy diapers."),
            WhiteCard(text: "A live studio audience."),
            WhiteCard(text: "The Great Depression."),
            WhiteCard(text: "A spastic nerd."),
            WhiteCard(text: "Rush Limbaugh's soft, shitty body."),
            WhiteCard(text: "Tickling Sean Hannity, even after he tells you to stop."),
            WhiteCard(text: "Stalin."),
            WhiteCard(text: "Brown people."),
            WhiteCard(text: "Rehab."),
            WhiteCard(text: "Capturing Newt Gingrich and forcing him to dance in a monkey suit."),
            WhiteCard(text: "Battlefield amputations."),
            WhiteCard(text: "An uppercut."),
            WhiteCard(text: "Shiny objects."),
            WhiteCard(text: "An ugly face."),
            WhiteCard(text: "Menstrual rage."),
            WhiteCard(text: "A bitch slap."),
            WhiteCard(text: "One trillion dollars."),
            WhiteCard(text: "Chunks of dead prostitute."),
            WhiteCard(text: "The entire Mormon Tabernacle Choir."),
            WhiteCard(text: "The female orgasm."),
            WhiteCard(text: "Extremely tight pants."),
            WhiteCard(text: "The Boy Scouts of America."),
            WhiteCard(text: "Stormtroopers."),
            WhiteCard(text: "Throwing a virgin into a volcano.")
        ]
    }
}
